version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

parameters:
  marketplace-deploy:
    type: boolean
    default: false 

commands:
  zip-source:
    parameters:
      target:
        type: string
      outputdir:
        type: string
    steps:
      - run:
          name: "Create Archive"
          command: |
            \cp -r ".pluginconfig/<<parameters.target>>/." "./"
            mkdir -p "<<parameters.outputdir>>/"
            stashName=`git stash create`;
            git archive -o "<<parameters.outputdir>>/speckle-unreal-UE<<parameters.target>>.zip" --worktree-attributes --prefix="speckle-unreal/" $stashName

  add-source-copyright:
    parameters:
      copyright-string:
        type: string
    steps:
      - run: #Remove BOM header, then add copyright comment
          name: "Add copyright notice to source files"
          command: |
            shopt -s globstar
            for file in Source/**/*.{cpp,hpp,c,h,cs};
              do if [ -f $file ]; then
                sed -i '1s/^\xEF\xBB\xBF//' $file;
                sed -i '1s/^/\/\/ <<parameters.copyright-string>>\n/' $file;
                echo "added copyright notice to $file";
              fi;
            done;

jobs:
  generate-source-zip:
    docker:
      - image: cimg/base:stable
    parameters:
      target:
        type: string
    steps:
      - checkout
      - add-source-copyright:
          copyright-string: "Copyright AEC SYSTEMS 2023"
      - zip-source:
            target: <<parameters.target>>
            outputdir: "output/unreal/<<parameters.target>>"
      - store_artifacts:
          path: "output/unreal/<<parameters.target>>"
          destination: "unreal-marketplace/<<parameters.target>>"
      - persist_to_workspace:
          root: ./
          paths:
            - "output/unreal/<<parameters.target>>"

  marketplace-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ./
      - aws-s3/copy:
          arguments: "--recursive --endpoint=https://$SPACES_REGION.digitaloceanspaces.com --acl public-read"
          aws-access-key-id: SPACES_KEY
          aws-region: SPACES_REGION
          aws-secret-access-key: SPACES_SECRET
          from: '"output"'
          to: s3://speckle-releases/installers/

workflows:
  marketplace-publish:
    when: <<pipeline.parameters.marketplace-deploy>>
    jobs:
      - generate-source-zip:
          name: "Generate Source Archive UE4.27"
          target: "4.27"
      - generate-source-zip:
          name: "Generate Source Archive UE5.0"
          target: "5.0"
      - generate-source-zip:
          name: "Generate Source Archive UE5.1"
          target: "5.1"      
      - generate-source-zip:
          name: "Generate Source Archive UE5.2"
          target: "5.2"
      - generate-source-zip:
          name: "Generate Source Archive UE5.3"
          target: "5.3"
      - generate-source-zip:
          name: "Generate Source Archive UE5.4"
          target: "5.4"
      - marketplace-deploy:
          name: "Deploy to marketplace"
          context: do-spaces-speckle-releases
          requires: 
            - "Generate Source Archive UE4.27"
            - "Generate Source Archive UE5.0"
            - "Generate Source Archive UE5.1"
            - "Generate Source Archive UE5.2"
            - "Generate Source Archive UE5.3"
            - "Generate Source Archive UE5.4"
